title: Rey Blume
email: reykunda@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is Rey Blume's website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://reykunda.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  reykunda

repository: "reykunda/reykunda.github.io"

# Build settings
markdown: kramdown
# theme: minima
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
